### ISSUE TITLE
panic: Error execing source pipeline: redis: nil

### ISSUE THREAD

**Issue by scalp42** [getlantern/redistrict#2]
Hi @myleshorton,

Thanks for the tool!

While trying to test it, I'm running into the following issue:

```
019-07-19T07:18:49.546Z        INFO    cmd/root.go:175 Connecting to destination redis
2019-07-19T07:18:49.546Z        INFO    cmd/root.go:178 Connecting to source redis
KEYS * 320018 / 663107 [==================================================================>-----------------------------------------------------------------------]  48.26% 06m48s
panic: Error execing source pipeline: redis: nil

goroutine 1 [running]:
github.com/getlantern/redistrict/cmd.(*migrator).write(0xc000152000, 0xc00002e180, 0xaae0a0, 0xc0001a0000, 0xc000026100)
        /opt/go/src/github.com/getlantern/redistrict/cmd/root.go:331 +0x864
github.com/getlantern/redistrict/cmd.(*migrator).migrateKeys(0xc000152000)
        /opt/go/src/github.com/getlantern/redistrict/cmd/root.go:305 +0x381
github.com/getlantern/redistrict/cmd.(*migrator).migrate(0xc000152000, 0xec31c0, 0xc0000cc8a0, 0x0, 0x6)
        /opt/go/src/github.com/getlantern/redistrict/cmd/root.go:239 +0xe9
github.com/spf13/cobra.(*Command).execute(0xec31c0, 0xc0000d0010, 0x6, 0x6, 0xec31c0, 0xc0000d0010)
        /opt/go/src/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xec31c0, 0x0, 0x0, 0x1388)
        /opt/go/src/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /opt/go/src/github.com/spf13/cobra/command.go:864
github.com/getlantern/redistrict/cmd.Execute()
        /opt/go/src/github.com/getlantern/redistrict/cmd/root.go:105 +0x32
main.main()
        /opt/go/src/github.com/getlantern/redistrict/main.go:6 +0x20

real    6m28.717s
user    0m4.566s
sys     0m8.865s
```

Do you have any idea by any chance?

Thanks!

**Comment by joesis** [comment]
Per https://godoc.org/gopkg.in/redis.v3 it means "Redis nil reply, .e.g. when key does not exist.".

**Comment by scalp42** [comment]
I see, I'm wondering if we could just rescue the error with a best effort flag.
